spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true

  datasource:
    username: study
    password: study
    url: jdbc:postgresql://localhost:5432/study
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE